// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
